[settings]
SECRET_KEY=django-insecure-dev-7!a*ymfhv12-change-in-production
DEBUG=True

DB_ENGINE=django.db.backends.mysql

; LOCAL (descomentar para desarrollo sin Railway)
; DB_ENGINE=django.db.backends.sqlite3
; DB_NAME=db.sqlite3
; DB_USER=
; DB_PASSWORD=
; DB_HOST=
; DB_PORT=

; PRODUCTION — Railway MySQL (proxy externo)
DB_NAME=railway
DB_USER=root
DB_PASSWORD=pfIIMaRyHiWbsiEPYFjjkWKpejNoYfpC
DB_HOST=gondola.proxy.rlwy.net
DB_PORT=11522

ALLOWED_HOSTS=localhost,127.0.0.1,semaforo-inteligente-production.up.railway.app
CORS_ALLOWED_ORIGINS=http://localhost:4200

IOT_API_KEY=dev-iot-secret-change-me

JWT_ACCESS_TOKEN_LIFETIME=60
JWT_REFRESH_TOKEN_LIFETIME=1440
