# Generated by Django 6.0.4 on 2026-04-30 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_main', models.BooleanField(default=False)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='semaforo.intersection')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('RED', 'Rojo'), ('YELLOW', 'Amarillo'), ('GREEN', 'Verde')], default='RED', max_length=10)),
                ('road', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_light', to='semaforo.road')),
            ],
        ),
    ]
