# Generated by Django 5.2 on 2026-05-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semaforo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intersection',
            options={'verbose_name': 'Intersección', 'verbose_name_plural': 'Intersecciones'},
        ),
        migrations.AlterModelOptions(
            name='road',
            options={'ordering': ['-is_main', 'name'], 'verbose_name': 'Vía', 'verbose_name_plural': 'Vías'},
        ),
        migrations.AlterModelOptions(
            name='trafficlight',
            options={'verbose_name': 'Semáforo', 'verbose_name_plural': 'Semáforos'},
        ),
        migrations.AddField(
            model_name='trafficlight',
            name='manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trafficlight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='intersection',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
