# Generated by Django 5.2.13 on 2026-06-09 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGIN_FAILED', 'Intento de login fallido'), ('USER_CREATED', 'Usuario creado'), ('USER_UPDATED', 'Usuario actualizado'), ('PASSWORD_RESET_REQUESTED', 'Solicitud de restablecimiento de contraseña'), ('PASSWORD_RESET_DONE', 'Contraseña restablecida'), ('ROLE_ASSIGNED', 'Rol asignado'), ('LIGHT_OVERRIDE', 'Control manual de semáforo'), ('LIGHT_AUTO', 'Semáforo liberado a automático')], db_index=True, max_length=40)),
                ('usuario_str', models.CharField(blank=True, max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
