# Generated by Django 6.0.4 on 2026-04-30 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semaforo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_detected', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semaforo.road')),
            ],
        ),
    ]
