# Generated by Django 5.2.13 on 2026-05-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficrecord',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trafficrecord',
            name='vehicle_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
