# Generated by Django 5.2.13 on 2026-05-17 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semaforo', '0003_trafficlight_green_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('traffic_light_state', models.CharField(max_length=10)),
                ('vehicle_count', models.PositiveSmallIntegerField(default=1)),
                ('confidence', models.FloatField(default=0.0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='infractions/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('VERIFIED', 'Verificada'), ('DISMISSED', 'Desestimada')], default='PENDING', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='semaforo.road')),
            ],
            options={
                'verbose_name': 'Infracción',
                'verbose_name_plural': 'Infracciones',
                'ordering': ['-timestamp'],
            },
        ),
    ]
