# Generated by Django 5.2.13 on 2026-05-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infractions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infraction',
            name='photo',
        ),
        migrations.AddField(
            model_name='infraction',
            name='photo_b64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infraction',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa'),
        ),
    ]
