# Generated by Django 5.2 on 2026-05-06 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensores'},
        ),
    ]
