# Generated by Django 5.2.13 on 2026-05-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_alter_sensor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='vehicle_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
