# Generated by Django 5.2.13 on 2026-05-10 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semaforo', '0002_alter_intersection_options_alter_road_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ESP32', 'ESP32'), ('SENSOR', 'Sensor'), ('DISPLAY', 'Display'), ('OTRO', 'Otro')], default='ESP32', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('firmware_version', models.CharField(blank=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('estado', models.CharField(choices=[('ONLINE', 'En línea'), ('OFFLINE', 'Fuera de línea'), ('ERROR', 'Error')], default='OFFLINE', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='semaforo.intersection')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['nombre'],
            },
        ),
    ]
